config/routes.rb
Ticketmeister::Application.routes.draw do
  resources :gigs

  resources :concerts

  resources :bands

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :category, :name
  
  has_many :gigs
  has_many :concerts, :through => :gigs
  
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :held_on, :venue
  
  has_many :gigs
  has_many :bands, :through => :gigs
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  attr_accessible :band_id, :compensation, :concert_id
  
  belongs_to :band
  belongs_to :concert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bands }
    end
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @band }
    end
  end

  # GET /bands/new
  # GET /bands/new.json
  def new
    @band = Band.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @band }
    end
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(params[:band])

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render json: @band, status: :created, location: @band }
      else
        format.html { render action: "new" }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bands/1
  # PUT /bands/1.json
  def update
    @band = Band.find(params[:id])

    respond_to do |format|
      if @band.update_attributes(params[:band])
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concerts }
    end
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    @concert = Concert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/new
  # GET /concerts/new.json
  def new
    @concert = Concert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/1/edit
  def edit
    @concert = Concert.find(params[:id])
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render json: @concert, status: :created, location: @concert }
      else
        format.html { render action: "new" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concerts/1
  # PUT /concerts/1.json
  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gigs }
    end
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gig }
    end
  end

  # GET /gigs/new
  # GET /gigs/new.json
  def new
    @gig = Gig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gig }
    end
  end

  # GET /gigs/1/edit
  def edit
    @gig = Gig.find(params[:id])
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(params[:gig])

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render json: @gig, status: :created, location: @gig }
      else
        format.html { render action: "new" }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gigs/1
  # PUT /gigs/1.json
  def update
    @gig = Gig.find(params[:id])

    respond_to do |format|
      if @gig.update_attributes(params[:gig])
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig = Gig.find(params[:id])
    @gig.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Listing bands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bands.each do |band| %>
  <tr>
    <td><%= band.name %></td>
    <td><%= band.category %></td>
    <td><%= link_to 'Show', band %></td>
    <td><%= link_to 'Edit', edit_band_path(band) %></td>
    <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @band.name %>
</p>

<p>
  <b>Category:</b>
  <%= @band.category %>
</p>

<ul>
<% @band.concerts.each do |concert| %>
  <li>Playing at <%=  concert.venue %> on <%= concert.held_on %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :held_on %><br />
    <%= f.date_select :held_on %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<h1>Listing concerts</h1>

<table>
  <tr>
    <th>Held on</th>
    <th>Venue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @concerts.each do |concert| %>
  <tr>
    <td><%= concert.held_on %></td>
    <td><%= concert.venue %></td>
    <td><%= link_to 'Show', concert %></td>
    <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
    <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Held on:</b>
  <%= @concert.held_on %>
</p>

<p>
  <b>Venue:</b>
  <%= @concert.venue %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/gigs/_form.html.erb
<%= form_for(@gig) do |f| %>
  <% if @gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
      <% @gig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band_id %><br />
    <%= f.collection_select :band_id, Band.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :concert_id %><br />
    <%= f.collection_select :concert_id, Concert.all, :id, :venue %>
  </div>
  <div class="field">
    <%= f.label :compensation %><br />
    <%= f.number_field :compensation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gigs/edit.html.erb
<h1>Editing gig</h1>

<%= render 'form' %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

app/views/gigs/index.html.erb
<h1>Listing gigs</h1>

<table>
  <tr>
    <th>Band</th>
    <th>Concert</th>
    <th>Compensation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gigs.each do |gig| %>
  <tr>
    <td><%= gig.band_id %></td>
    <td><%= gig.concert_id %></td>
    <td><%= gig.compensation %></td>
    <td><%= link_to 'Show', gig %></td>
    <td><%= link_to 'Edit', edit_gig_path(gig) %></td>
    <td><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gig', new_gig_path %>

app/views/gigs/new.html.erb
<h1>New gig</h1>

<%= render 'form' %>

<%= link_to 'Back', gigs_path %>

app/views/gigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Band:</b>
  <%= @gig.band_id %>
</p>

<p>
  <b>Concert:</b>
  <%= @gig.concert_id %>
</p>

<p>
  <b>Compensation:</b>
  <%= @gig.compensation %>
</p>


<%= link_to 'Edit', edit_gig_path(@gig) %> |
<%= link_to 'Back', gigs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketmeister</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>